NEI<-readRDS("summarySCC_PM25.rds")
SCC<-readRDS("Source_Classification_Code.rds")
subNEI<-subset(NEI, NEI$fips =="24510")
subNEI$year<-as.factor(subNEI$year)
data<-tapply(subNEI$Emissions,subNEI$year,sum)
png("plot2.png",bg="transparent")
barplot(data, xlab="Year",ylab="PM2.5 in Kilotons", col="blue", main="Total Emission - Baltimore City, MD")
dev.off()
rm(list=ls())
